### PR TITLE
fix: make getIntermediateOutputFiles work again

### LINKED ISSUE #17: Issue with `getIntermediateOutputFiles`
Now there is an error thrown (and no crate created) when trying to use the function `getIntermediateOutputFiles`:
```bash
Dec-03 14:13:47.950 [main] DEBUG nextflow.Session - Failed to invoke observer completion handler: nextflow.prov.ProvObserver@5f233f9
java.lang.IllegalArgumentException: 'other' is different type of Path
	at java.base/sun.nio.fs.UnixPath.relativize(UnixPath.java:406)
	at java.base/sun.nio.fs.UnixPath.relativize(UnixPath.java:51)
	at nextflow.prov.WrrocRenderer$_getIntermediateOutputFiles_closure27.doCall(WrrocRenderer.groovy:571)
	at nextflow.prov.WrrocRenderer$_getIntermediateOutputFiles_closure27.call(WrrocRenderer.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3661)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3646)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3692)
	at nextflow.prov.WrrocRenderer.getIntermediateOutputFiles(WrrocRenderer.groovy:562)
	at nextflow.prov.WrrocRenderer.render(WrrocRenderer.groovy:84)
	at nextflow.prov.ProvObserver.onFlowComplete(ProvObserver.groovy:121)
	at nextflow.Session.notifyFlowComplete(Session.groovy:1155)
	at nextflow.Session.shutdown0(Session.groovy:749)
	at nextflow.Session.destroy(Session.groovy:694)
	at nextflow.script.ScriptRunner.shutdown(ScriptRunner.groovy:260)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:146)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:376)
	at nextflow.cli.Launcher.run(Launcher.groovy:503)
	at nextflow.cli.Launcher.main(Launcher.groovy:658)
```

This seems to be the offending part in the code:
```groovy
                        // Find the relative path from workdir
                        Path relativePath = workdir.relativize(taskOutputFilePath)
 ```

### PR DESCRIPTION
**Pull request by famosab**
This is trying to solve #17. But still throws errors. @fbartusch maybe you have a better idea.

### CODE REVIEW

**Comment by fbartusch** [comment]
Can you provide me with your BioHackathon24 pipeline and data? Then I can try to reproduce it.
I programmed everything with nf-core/demo as test case and I think there were no errors.

**Comment by famosab** [comment]
Everything you need should be here: https://github.com/famosab/wrrocmetatest or linked in the README of that pipeline :) Thanks!

Plgin version needs to be updated to 1.3.0 probably though (in the testdata.config file).

**Comment by fbartusch** [comment]
The error occurs also with nf-prov/demo. I'm debugging the `getIntermediateOutputFiles` function. The good old println-Debugging helps a bit:
I'm printing the values in the two for loops:

This iteration is nice and works as expected:
```
taskOutputParam:fileoutparam<0:1>=[/tmp/nf-prov/1.3.0/workdir/38/9822f0faf19977ec8b14c815c2d227/SAMPLE2_PE_sample2_R1.fastq.gz, /tmp/nf-prov/1.3.0/workdir/38/9822f0faf19977ec8b14c815c2d227/SAMPLE2_PE_sample2_R2.fastq.gz]
taskOutputParam.getValue(): [/tmp/nf-prov/1.3.0/workdir/38/9822f0faf19977ec8b14c815c2d227/SAMPLE2_PE_sample2_R1.fastq.gz, /tmp/nf-prov/1.3.0/workdir/38/9822f0faf19977ec8b14c815c2d227/SAMPLE2_PE_sample2_R2.fastq.gz]
taskOutputParam.getValue().getClass(): class java.util.ArrayList
        taskOutputFile: /tmp/nf-prov/1.3.0/workdir/38/9822f0faf19977ec8b14c815c2d227/SAMPLE2_PE_sample2_R1.fastq.gz
        taskOutputFile: /tmp/nf-prov/1.3.0/workdir/38/9822f0faf19977ec8b14c815c2d227/SAMPLE2_PE_sample2_R2.fastq.gz

```

This is an example of a problematic iteration:

```
taskOutputParam:fileoutparam<1>=/tmp/nf-prov/1.3.0/workdir/38/9822f0faf19977ec8b14c815c2d227/versions.yml
taskOutputParam.getValue(): /tmp/nf-prov/1.3.0/workdir/38/9822f0faf19977ec8b14c815c2d227/versions.yml
taskOutputParam.getValue().getClass(): class sun.nio.fs.UnixPath
        taskOutputFile: tmp
        taskOutputFile: nf-prov
        taskOutputFile: 1.3.0
        taskOutputFile: workdir
        taskOutputFile: 38
        taskOutputFile: 9822f0faf19977ec8b14c815c2d227
        taskOutputFile: versions.yml

```

This time `taskOutputParam` is a `UnixPath` and the second for-loop seems to iterate over the path elements. I don't know why it shows this behaviour. I haven't seen this before. I think a check for handling `UnixPath`  in it's own way will solve the issue. I'm now working on the solution.

**Comment by fbartusch** [comment]
@famosab I hope I fixed these problems. Your `wrrocmetatest` and also my `nf-prov/demo` work again.
I tried to make the mapping of files into the crate a bit more reliable and tested your pipeline with different locations for input data and crate directory.

Can you test it and merge if it works for you?

**Pull request merged**
